---
title: "characteristics_table_generation"
author: "Cirun"
date: "2/23/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Tutorial:
https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html

```{r}
library(data.table)
library(openxlsx)
library(table1)
library(MatchIt) 
```

change it here
```{r}
setwd("/Users/cirun/Desktop/TDS_Project_Group5")
```


```{r}
mydata=readRDS("0309_31cols_recoded_raw.rds")
mycoding=read.csv("Codings_Showcase.csv")
```

```{r}
get_coding <- function(code) {
    mycoding_field=mycoding[which(mycoding[,1]==code),]
    mycoding_field=mycoding_field[,-1]
    rownames(mycoding_field)=mycoding_field[,1]
    return(mycoding_field)
}
```

```{r}
rndr <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- mydata[[name]]
        s <- rep("", length(render.default(x=y, name=name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ mydata$outcome_status)$p.value
        } else {
            p <- chisq.test(table(y,droplevels(mydata$outcome_status)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits=3, eps=0.001))
        s
    } else {
        render.default(x=x, name=name, ...)
    }
}

rndr.strat <- function(label, n, ...) {
    ifelse(n==0, label, render.strat.default(label, n, ...))
}
```

### Demographics
```{r}
coding_sex = get_coding(9)
sex <- factor(mydata$X31.0.0, levels=coding_sex$Value,
         labels = coding_sex$Meaning)
label(sex) <- "Sex"

age_at_recuritment <- mydata$X21022.0.0
label(age_at_recuritment) <- "Age at recuritment"

label(mydata$ethnicity) <- "Ethnicity"

outcome_status <- mydata$outcome_status

outcome_status <- factor(outcome_status, levels = c(0, 1), labels = c("Control", "Case"))

tb1 <- table1(~ sex + age_at_recuritment + ethnic| outcome_status)
# , data = mydata,render=rndr, render.strat=rndr.strat
```

### Demographics with p-values
```{r}
coding_sex = get_coding(9)
sex <- factor(mydata$X31.0.0, levels=coding_sex$Value,
         labels = coding_sex$Meaning)
label(sex) <- "Sex"
mydata$sex = sex

age_at_recuritment <- mydata$X21022.0.0
label(age_at_recuritment) <- "Age at recuritment"
mydata$age_at_recuritment <- age_at_recuritment

label(mydata$ethnicity) <- "Ethnicity"

mydata$outcome_status <- factor(mydata$outcome_status, levels = c(0, 1, 2), labels = c("Control", "Case", "P-value"))

tb1 <- table1(~ sex + age_at_recuritment + ethnicity | outcome_status, data = mydata, droplevels = F, render=rndr, render.strat=rndr.strat)
```

### Social factors
```{r}
townsend_deprivation_index <- mydata$X189.0.0
label(townsend_deprivation_index) <- "Townsend deprivation index"
mydata$townsend_deprivation_index <- townsend_deprivation_index

mydata$education <- factor(mydata$education)
label(mydata$education) <- "Education"
```

### Health risk factors
```{r}
mydata$bmi <- as.factor(mydata$bmi)
label(mydata$bmi) <- "BMI"

label(mydata$waist_hip_ratio) <- "Waist Hip circumference ratio"

smoke <- as.factor(mydata$smoking_status)
label(smoke) <- "Smoking status"
mydata$smoke <- smoke

alcohol <- as.factor(mydata$alcohol_status)
label(alcohol) <- "Alcohol intake frequency"
mydata$alcohol <- alcohol

active_days <- mydata$active_days
label(active_days) <- "Physical active days"
mydata$active_days <- active_days

Cardiovascular <- factor(mydata$Cardiovascular,labels = c("No", "Yes"))
label(Cardiovascular) <- "Cardiovascular disease"
mydata$Cardiovascular <- Cardiovascular

Hypertension <- factor(mydata$Hypertension,labels = c("No", "Yes"))
label(Hypertension) <- "Hypertension"
mydata$Hypertension <- Hypertension

Diabetes <- factor(mydata$Diabetes,labels = c("No", "Yes"))
label(Diabetes) <- "Diabetes"
mydata$Diabetes <- Diabetes

Respiratory <- factor(mydata$Respiratory,labels = c("No", "Yes"))
label(Respiratory) <- "Respiratory disease"
mydata$Respiratory <- Respiratory
#tb3 <- table1(~ bmi + waist_circumference + hip_circumference + smoke + alcohol | outcome_status)
```

### Breast cancer related variables

```{r}
coding_breast_cancer_screening <- get_coding(100349)
breast_cancer_screening <- factor(mydata$X2674.0.0, levels=coding_breast_cancer_screening$Value, labels = coding_breast_cancer_screening$Meaning)
label(breast_cancer_screening) <- "Breast cancer screening"
mydata$breast_cancer_screening <- breast_cancer_screening


family_history_BC <- mydata$family_history
label(family_history_BC) <- "Family breast cancer history"
mydata$family_history_BC <- family_history_BC
#tb4 <- table1(~ breast_cancer_screening | outcome_status)
```

### Reproductive variables
```{r}
menarche_age = as.double(mydata$menarche_age)
label(menarche_age) <- "Menarche age"
mydata$menarche_age <- menarche_age
  
coding_had_menopause <- get_coding(100579)
had_menopause <- factor(mydata$X2724.0.0, labels=coding_had_menopause$Meaning)
label(had_menopause) <- "Menopause status"
mydata$had_menopause <- had_menopause

number_of_live_births = as.numeric(mydata$X2734.0.0)
label(number_of_live_births) <- "Number of live births"
mydata$number_of_live_births <- number_of_live_births

ever_have_birth <- as.factor(mydata$ever_had_birth)
label(ever_have_birth) <- "Birth status"
mydata$ever_have_birth <- ever_have_birth

coding_termination <- get_coding(100349)
termination <- factor(mydata$X2774.0.0,levels=coding_termination$Value, labels=coding_termination$Meaning)
label(termination) <- "Termination status"
mydata$termination <- termination

coding_oral_contraceptive <- get_coding(100349)
oral_contraceptive <- factor(mydata$X2784.0.0,levels=coding_oral_contraceptive$Value, labels=coding_oral_contraceptive$Meaning)
label(oral_contraceptive) <- "Oral contraceptive status"
mydata$oral_contraceptive <- oral_contraceptive

coding_hrt<- get_coding(100349)
hrt <- factor(mydata$X2784.0.0,levels=coding_hrt$Value, labels=coding_hrt$Meaning)
label(hrt) <- "Hormone-replacement therapy status"
mydata$hrt <- hrt

#tb5 <- table1(~ menarche_age  + had_menopause + number_of_live_births + ever_have_birth + termination + oral_contraceptive + hrt | outcome_status)
```

### Biomakers
```{r eval=FALSE, include=FALSE}
triglycerides = biomakers$X30870.0.0
label(triglycerides) <- "Triglycerides"

glycated_haemoglobin = biomakers$X30750.0.0
label(glycated_haemoglobin) <- "Glycated haemoglobin (HbA1c)"

glucose = biomakers$X30740.0.0
label(glucose) <- "Glucose"

cholesterol = biomakers$X30760.0.0
label(cholesterol) <- "HDL cholesterol"

oestradiol = biomakers$X30800.0.0
label(oestradiol) <- "Oestradiol"

tb6 <- table1(~ triglycerides + glycated_haemoglobin + glucose + cholesterol + oestradiol)

tb6
```

Full table
```{r eval=FALSE, include=FALSE}
tb_full <- table1(~ sex + age_at_recuritment + ethnic + townsend_deprivation_index + bmi + waist_circumference + hip_circumference + smoke + alcohol + breast_cancer_screening + menarche_age  + had_menopause + number_of_live_births + ever_have_birth + termination + oral_contraceptive + hrt| outcome_status)
```

Full table with P-Value
```{r}
tb_full <- table1(~ sex + age_at_recuritment + ethnicity + education + bmi_cat + waist_hip_ratio + smoke + alcohol+ active_days + Cardiovascular + Diabetes + Hypertension + Respiratory + breast_cancer_screening + family_history_BC + menarche_age  + had_menopause + number_of_live_births + ever_have_birth + termination + oral_contraceptive + hrt| outcome_status, data = mydata, droplevels = F, render=rndr, render.strat=rndr.strat)
```